#! /bin/sh

sxhkd -c ~/.config/sxhkd/sxhkdrc &
albert &
dunst &
compton &
glava &

xinput set-prop 11 "libinput Natural Scrolling Enabled" 1

cd ~/Projects/Python/bar && pypy3 -m bar &
cd ~

nitrogen --restore

bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Discord Updater" state=floating
bspc rule -a mplayer2 state=floating
